[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.entry-points.pytest11]
schemashot = "typed_schema_shot.plugin"

[tool.hatch.build.targets.wheel]
packages = ["src/typed_schema_shot"]

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
